import React from 'react';
import {Composition, Folder} from 'remotion';
import {FORMATS, FPS} from './presets/formats';
import {EXAMPLES} from './examples/content';
import {
  BarChartReveal,
  BarChartRevealSchema,
  barChartRevealDuration,
  BeforeAfter,
  BeforeAfterSchema,
  beforeAfterDuration,
  BentoGrid,
  BentoGridSchema,
  bentoGridDuration,
  BulletCard,
  BulletCardSchema,
  bulletCardDuration,
  ChangelogCard,
  ChangelogCardSchema,
  changelogCardDuration,
  Countdown,
  CountdownSchema,
  countdownDuration,
  DonutBreakdown,
  DonutBreakdownSchema,
  donutBreakdownDuration,
  FeatureTrio,
  FeatureTrioSchema,
  featureTrioDuration,
  MetricCounter,
  MetricCounterSchema,
  metricCounterDuration,
  ModalExplainer,
  ModalExplainerSchema,
  modalExplainerDuration,
  ProductReveal,
  ProductRevealSchema,
  productRevealDuration,
  ScreenShowcase,
  ScreenShowcaseSchema,
  screenShowcaseDuration,
  SocialPost,
  SocialPostSchema,
  socialPostDuration,
  StaggeredWords,
  StaggeredWordsSchema,
  staggeredWordsDuration,
  StepList,
  StepListSchema,
  stepListDuration,
  StepTimeline,
  StepTimelineSchema,
  stepTimelineDuration,
  TypewriterLine,
  TypewriterLineSchema,
  typewriterLineDuration,
  UiCallout,
  UiCalloutSchema,
  uiCalloutDuration,
  UiFlow,
  UiFlowSchema,
  uiFlowDuration,
} from './templates';

const L = FORMATS.landscape;
const P = FORMATS.portrait;

/**
 * Every template is registered twice: 16:9 and 9:16. That is not a convenience,
 * it is the acceptance check — the validation matrix fails any template that
 * only survives its authoring aspect ratio.
 *
 * Note on editing: `defaultProps` here reference src/examples/content.ts, so
 * Remotion Studio's props editor will preview your changes but cannot save them
 * back to code. Inline an object literal on a composition if you want the Save
 * button to write into this file.
 */
export const RemotionRoot: React.FC = () => (
  <>
    <Folder name="Landscape-16x9">
      <Composition
        id="BarChartReveal"
        component={BarChartReveal}
        schema={BarChartRevealSchema}
        defaultProps={EXAMPLES.barChartReveal}
        durationInFrames={barChartRevealDuration(EXAMPLES.barChartReveal)}
        fps={FPS}
        width={L.width}
        height={L.height}
      />
      <Composition
        id="DonutBreakdown"
        component={DonutBreakdown}
        schema={DonutBreakdownSchema}
        defaultProps={EXAMPLES.donutBreakdown}
        durationInFrames={donutBreakdownDuration(EXAMPLES.donutBreakdown)}
        fps={FPS}
        width={L.width}
        height={L.height}
      />
      <Composition
        id="MetricCounter"
        component={MetricCounter}
        schema={MetricCounterSchema}
        defaultProps={EXAMPLES.metricCounter}
        durationInFrames={metricCounterDuration(EXAMPLES.metricCounter)}
        fps={FPS}
        width={L.width}
        height={L.height}
      />
      <Composition
        id="Countdown"
        component={Countdown}
        schema={CountdownSchema}
        defaultProps={EXAMPLES.countdown}
        durationInFrames={countdownDuration(EXAMPLES.countdown)}
        fps={FPS}
        width={L.width}
        height={L.height}
      />
      <Composition
        id="ChangelogCard"
        component={ChangelogCard}
        schema={ChangelogCardSchema}
        defaultProps={EXAMPLES.changelogCard}
        durationInFrames={changelogCardDuration(EXAMPLES.changelogCard)}
        fps={FPS}
        width={L.width}
        height={L.height}
      />
      <Composition
        id="BulletCard"
        component={BulletCard}
        schema={BulletCardSchema}
        defaultProps={EXAMPLES.bulletCard}
        durationInFrames={bulletCardDuration(EXAMPLES.bulletCard)}
        fps={FPS}
        width={L.width}
        height={L.height}
      />
      <Composition
        id="SocialPost"
        component={SocialPost}
        schema={SocialPostSchema}
        defaultProps={EXAMPLES.socialPost}
        durationInFrames={socialPostDuration(EXAMPLES.socialPost)}
        fps={FPS}
        width={L.width}
        height={L.height}
      />
      <Composition
        id="StaggeredWords"
        component={StaggeredWords}
        schema={StaggeredWordsSchema}
        defaultProps={EXAMPLES.staggeredWords}
        durationInFrames={staggeredWordsDuration(EXAMPLES.staggeredWords)}
        fps={FPS}
        width={L.width}
        height={L.height}
      />
      <Composition
        id="TypewriterLine"
        component={TypewriterLine}
        schema={TypewriterLineSchema}
        defaultProps={EXAMPLES.typewriterLine}
        durationInFrames={typewriterLineDuration(EXAMPLES.typewriterLine)}
        fps={FPS}
        width={L.width}
        height={L.height}
      />
      <Composition
        id="BeforeAfter"
        component={BeforeAfter}
        schema={BeforeAfterSchema}
        defaultProps={EXAMPLES.beforeAfter}
        durationInFrames={beforeAfterDuration(EXAMPLES.beforeAfter)}
        fps={FPS}
        width={L.width}
        height={L.height}
      />
      <Composition
        id="StepTimeline"
        component={StepTimeline}
        schema={StepTimelineSchema}
        defaultProps={EXAMPLES.stepTimeline}
        durationInFrames={stepTimelineDuration(EXAMPLES.stepTimeline)}
        fps={FPS}
        width={L.width}
        height={L.height}
      />
      <Composition
        id="StepList"
        component={StepList}
        schema={StepListSchema}
        defaultProps={EXAMPLES.stepList}
        durationInFrames={stepListDuration(EXAMPLES.stepList)}
        fps={FPS}
        width={L.width}
        height={L.height}
      />
      <Composition
        id="ScreenShowcase"
        component={ScreenShowcase}
        schema={ScreenShowcaseSchema}
        defaultProps={EXAMPLES.screenShowcase}
        durationInFrames={screenShowcaseDuration(EXAMPLES.screenShowcase)}
        fps={FPS}
        width={L.width}
        height={L.height}
      />
      <Composition
        id="UiFlow"
        component={UiFlow}
        schema={UiFlowSchema}
        defaultProps={EXAMPLES.uiFlow}
        durationInFrames={uiFlowDuration(EXAMPLES.uiFlow)}
        fps={FPS}
        width={L.width}
        height={L.height}
      />
      <Composition
        id="UiCallout"
        component={UiCallout}
        schema={UiCalloutSchema}
        defaultProps={EXAMPLES.uiCallout}
        durationInFrames={uiCalloutDuration(EXAMPLES.uiCallout)}
        fps={FPS}
        width={L.width}
        height={L.height}
      />
      <Composition
        id="ModalExplainer"
        component={ModalExplainer}
        schema={ModalExplainerSchema}
        defaultProps={EXAMPLES.modalExplainer}
        durationInFrames={modalExplainerDuration(EXAMPLES.modalExplainer)}
        fps={FPS}
        width={L.width}
        height={L.height}
      />
      <Composition
        id="BentoGrid"
        component={BentoGrid}
        schema={BentoGridSchema}
        defaultProps={EXAMPLES.bentoGrid}
        durationInFrames={bentoGridDuration(EXAMPLES.bentoGrid)}
        fps={FPS}
        width={L.width}
        height={L.height}
      />
      <Composition
        id="FeatureTrio"
        component={FeatureTrio}
        schema={FeatureTrioSchema}
        defaultProps={EXAMPLES.featureTrio}
        durationInFrames={featureTrioDuration(EXAMPLES.featureTrio)}
        fps={FPS}
        width={L.width}
        height={L.height}
      />
      <Composition
        id="ProductReveal"
        component={ProductReveal}
        schema={ProductRevealSchema}
        defaultProps={EXAMPLES.productReveal}
        durationInFrames={productRevealDuration(EXAMPLES.productReveal)}
        fps={FPS}
        width={L.width}
        height={L.height}
      />
    </Folder>

    <Folder name="Portrait-9x16">
      <Composition
        id="BarChartReveal-9x16"
        component={BarChartReveal}
        schema={BarChartRevealSchema}
        defaultProps={EXAMPLES.barChartReveal}
        durationInFrames={barChartRevealDuration(EXAMPLES.barChartReveal)}
        fps={FPS}
        width={P.width}
        height={P.height}
      />
      <Composition
        id="DonutBreakdown-9x16"
        component={DonutBreakdown}
        schema={DonutBreakdownSchema}
        defaultProps={EXAMPLES.donutBreakdown}
        durationInFrames={donutBreakdownDuration(EXAMPLES.donutBreakdown)}
        fps={FPS}
        width={P.width}
        height={P.height}
      />
      <Composition
        id="MetricCounter-9x16"
        component={MetricCounter}
        schema={MetricCounterSchema}
        defaultProps={EXAMPLES.metricCounter}
        durationInFrames={metricCounterDuration(EXAMPLES.metricCounter)}
        fps={FPS}
        width={P.width}
        height={P.height}
      />
      <Composition
        id="Countdown-9x16"
        component={Countdown}
        schema={CountdownSchema}
        defaultProps={EXAMPLES.countdown}
        durationInFrames={countdownDuration(EXAMPLES.countdown)}
        fps={FPS}
        width={P.width}
        height={P.height}
      />
      <Composition
        id="ChangelogCard-9x16"
        component={ChangelogCard}
        schema={ChangelogCardSchema}
        defaultProps={EXAMPLES.changelogCard}
        durationInFrames={changelogCardDuration(EXAMPLES.changelogCard)}
        fps={FPS}
        width={P.width}
        height={P.height}
      />
      <Composition
        id="BulletCard-9x16"
        component={BulletCard}
        schema={BulletCardSchema}
        defaultProps={EXAMPLES.bulletCard}
        durationInFrames={bulletCardDuration(EXAMPLES.bulletCard)}
        fps={FPS}
        width={P.width}
        height={P.height}
      />
      <Composition
        id="SocialPost-9x16"
        component={SocialPost}
        schema={SocialPostSchema}
        defaultProps={EXAMPLES.socialPost}
        durationInFrames={socialPostDuration(EXAMPLES.socialPost)}
        fps={FPS}
        width={P.width}
        height={P.height}
      />
      <Composition
        id="StaggeredWords-9x16"
        component={StaggeredWords}
        schema={StaggeredWordsSchema}
        defaultProps={EXAMPLES.staggeredWords}
        durationInFrames={staggeredWordsDuration(EXAMPLES.staggeredWords)}
        fps={FPS}
        width={P.width}
        height={P.height}
      />
      <Composition
        id="TypewriterLine-9x16"
        component={TypewriterLine}
        schema={TypewriterLineSchema}
        defaultProps={EXAMPLES.typewriterLine}
        durationInFrames={typewriterLineDuration(EXAMPLES.typewriterLine)}
        fps={FPS}
        width={P.width}
        height={P.height}
      />
      <Composition
        id="BeforeAfter-9x16"
        component={BeforeAfter}
        schema={BeforeAfterSchema}
        defaultProps={EXAMPLES.beforeAfter}
        durationInFrames={beforeAfterDuration(EXAMPLES.beforeAfter)}
        fps={FPS}
        width={P.width}
        height={P.height}
      />
      <Composition
        id="StepTimeline-9x16"
        component={StepTimeline}
        schema={StepTimelineSchema}
        defaultProps={EXAMPLES.stepTimeline}
        durationInFrames={stepTimelineDuration(EXAMPLES.stepTimeline)}
        fps={FPS}
        width={P.width}
        height={P.height}
      />
      <Composition
        id="StepList-9x16"
        component={StepList}
        schema={StepListSchema}
        defaultProps={EXAMPLES.stepList}
        durationInFrames={stepListDuration(EXAMPLES.stepList)}
        fps={FPS}
        width={P.width}
        height={P.height}
      />
      <Composition
        id="ScreenShowcase-9x16"
        component={ScreenShowcase}
        schema={ScreenShowcaseSchema}
        defaultProps={EXAMPLES.screenShowcase}
        durationInFrames={screenShowcaseDuration(EXAMPLES.screenShowcase)}
        fps={FPS}
        width={P.width}
        height={P.height}
      />
      <Composition
        id="UiFlow-9x16"
        component={UiFlow}
        schema={UiFlowSchema}
        defaultProps={EXAMPLES.uiFlow}
        durationInFrames={uiFlowDuration(EXAMPLES.uiFlow)}
        fps={FPS}
        width={P.width}
        height={P.height}
      />
      <Composition
        id="UiCallout-9x16"
        component={UiCallout}
        schema={UiCalloutSchema}
        defaultProps={EXAMPLES.uiCallout}
        durationInFrames={uiCalloutDuration(EXAMPLES.uiCallout)}
        fps={FPS}
        width={P.width}
        height={P.height}
      />
      <Composition
        id="ModalExplainer-9x16"
        component={ModalExplainer}
        schema={ModalExplainerSchema}
        defaultProps={EXAMPLES.modalExplainer}
        durationInFrames={modalExplainerDuration(EXAMPLES.modalExplainer)}
        fps={FPS}
        width={P.width}
        height={P.height}
      />
      <Composition
        id="BentoGrid-9x16"
        component={BentoGrid}
        schema={BentoGridSchema}
        defaultProps={EXAMPLES.bentoGrid}
        durationInFrames={bentoGridDuration(EXAMPLES.bentoGrid)}
        fps={FPS}
        width={P.width}
        height={P.height}
      />
      <Composition
        id="FeatureTrio-9x16"
        component={FeatureTrio}
        schema={FeatureTrioSchema}
        defaultProps={EXAMPLES.featureTrio}
        durationInFrames={featureTrioDuration(EXAMPLES.featureTrio)}
        fps={FPS}
        width={P.width}
        height={P.height}
      />
      <Composition
        id="ProductReveal-9x16"
        component={ProductReveal}
        schema={ProductRevealSchema}
        defaultProps={EXAMPLES.productReveal}
        durationInFrames={productRevealDuration(EXAMPLES.productReveal)}
        fps={FPS}
        width={P.width}
        height={P.height}
      />
    </Folder>
  </>
);
